# Generated by Django 3.2.9 on 2022-02-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'empty'), (1, 'scree')], default=0)),
                ('value', models.TextField()),
            ],
        ),
    ]
