# Generated by Django 3.2.9 on 2022-02-16 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote', '0002_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='screenshot',
            new_name='image',
        ),
    ]
