# Generated by Django 3.2.9 on 2022-02-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'credit'), (1, 'debit')], default=0)),
                ('name', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('installments', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('fixed', models.BooleanField()),
            ],
        ),
    ]
