# Generated by Django 3.2.9 on 2022-02-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='financial',
            new_name='Payment',
        ),
    ]
