# Generated by Django 3.2.9 on 2022-02-21 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_rename_financial_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
