# Generated by Django 3.2.9 on 2022-02-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_payment_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'empty'), (1, 'projection'), (2, 'calculated'), (3, 'accounted')], default=0)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
