# Generated by Django 3.2.9 on 2021-11-26 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('file_path', models.TextField()),
                ('file_type', models.CharField(max_length=10)),
                ('playing', models.BooleanField()),
            ],
        ),
    ]
