# Generated by Django 3.2.9 on 2022-01-27 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_media_playing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='playing',
            new_name='status',
        ),
    ]
